<?php

namespace App\Models\Lists;

use \Bitrix\Main\Entity\ReferenceField;
use Bitrix\Main\ORM\Fields\Relations\Reference;
use App\Models\AbstractIblockPropertyValuesTable;

class CarsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 21;

   /*  public static function getMap(): array
    {
        $map = [
            'CITY' => new ReferenceField(  
                'CITY', 
                CityPropertyValuesTable::class, 
                ['=this.CITY_ID' => 'ref.IBLOCK_ELEMENT_ID']
            ),
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    } */
}
