<?php

namespace App\Models\Lists;

use \Bitrix\Main\Entity\ReferenceField;
use App\Models\AbstractIblockPropertyValuesTable;

class CountryPropertyValuesTable extends AbstractIblockPropertyValuesTable 
{
    public const IBLOCK_ID = 19;

    public static function getMap(): array
    {
        $map = [
            'CITYNAME' => new ReferenceField(  
                'CITYNAME', 
                CityPropertyValuesTable::class, 
                ['=this.CITIES' => 'ref.IBLOCK_ELEMENT_ID']
            ),
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}